# Generated by Django 3.2.16 on 2022-10-20 14:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import carbon.apps.base.utils.media_filename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date/time created"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to=carbon.apps.base.utils.media_filename.handle_filename,
                        verbose_name="Image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("SUSPENDED", "SUSPENDED"), ("ACTIVE", "ACTIVE")],
                        default="ACTIVE",
                        max_length=20,
                        null=True,
                        verbose_name="Customer Status",
                    ),
                ),
                (
                    "home_address",
                    models.CharField(max_length=256, verbose_name="Home Address"),
                ),
                (
                    "work_address",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Work Address",
                    ),
                ),
                ("city", models.CharField(max_length=256, verbose_name="Address City")),
                (
                    "created_by",
                    models.CharField(max_length=256, verbose_name="Created by"),
                ),
                (
                    "modified_by",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
                "ordering": ("-created",),
            },
        ),
    ]
